@plzwork_HostAddress = http://localhost:5085

GET {{plzwork_HostAddress}}/tasks
Accept: application/json

###

POST {{plzwork_HostAddress}}/tasks
Content-Type: application/json

{
    "id": 999,
    "name": "hi",
    "dueDate": "2026-07-08T12:00:00Z",
    "isCompleted": false
}


### 

GET {{plzwork_HostAddress}}/tasks/2

###

DELETE {{plzwork_HostAddress}}/tasks/1

###

PUT {{plzwork_HostAddress}}/tasks/2
Content-Type: application/json

{
  "name": "Updated task",
  "dueDate": "2026-08-25T12:00:00Z",
  "isCompleted": true
}