@plzwork_HostAddress = http://localhost:5085

GET {{plzwork_HostAddress}}/tasks
Accept: application/json
Authorization: Bearer {{login.response.body.$.token}}

### CREATE NEW TASK

POST {{plzwork_HostAddress}}/tasks
Content-Type: application/json

{
    "id": 999,
    "name": "hi",
    "dueDate": "2026-07-08T12:00:00Z",
    "isCompleted": false
}


### GET BY ID

GET {{plzwork_HostAddress}}/tasks/2

### DELETE

DELETE {{plzwork_HostAddress}}/tasks/1

### UPDATE

PUT {{plzwork_HostAddress}}/tasks/2
Content-Type: application/json

{
  "name": "Updated task",
  "dueDate": "2026-08-25T12:00:00Z",
  "isCompleted": true
}

### REGISTER

POST {{plzwork_HostAddress}}/auth/register
Content-Type: application/json

{
    "username": "testuser",
    "password": "password123"
}

### LOGIN

# @name login
POST {{plzwork_HostAddress}}/auth/login
Content-Type: application/json

{
    "username": "testuser",
    "password": "password123"
}